# Generated by Django 5.0.6 on 2024-06-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('phoneNo', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('referedBy', models.CharField(blank=True, max_length=100)),
                ('referalCode', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
