# Generated by Django 5.0.6 on 2024-06-05 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referedBy',
            new_name='referred_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phoneNo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referalCode',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=0, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91 1234567890'.", regex='^\\+91 \\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
    ]
