# Generated by Django 5.0.6 on 2024-06-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='course1_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='course2_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='course3_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
