# Generated by Django 5.0.6 on 2024-06-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_reset_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.user'),
        ),
    ]
