# Generated by Django 5.0.6 on 2024-06-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_commission_user_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
    ]
