# Generated by Django 5.0.6 on 2024-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_people_refered',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
