# Generated by Django 5.0.6 on 2024-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_no_people_refered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_people_refered',
            field=models.IntegerField(default=0),
        ),
    ]
