# Generated by Django 5.0.6 on 2024-06-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_user_no_people_refered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='no_people_refered',
        ),
    ]
