# Generated by Django 5.0.6 on 2024-06-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_user_no_people_refered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='overall_earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='settlement_amt',
            field=models.IntegerField(default=0),
        ),
    ]
