# Generated by Django 5.0.6 on 2024-06-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_overall_earnings_user_settlement_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level1_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='level1_referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level1_referrals', to='app.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='level2_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='level2_referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level2_referrals', to='app.user'),
        ),
    ]
