# Generated by Django 5.0.6 on 2024-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_course_remove_user_level1_commission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='commission_percent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
    ]
