# Generated by Django 4.1.13 on 2024-07-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_user_razorpay_payment_id_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='razorpay_payment_id_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
