# Generated by Django 4.1.13 on 2024-09-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_user_razorpay_payment_id_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='no_people_refered',
            new_name='no_people_referred',
        ),
    ]
